settings:
  legacy:
    force: false
    interval: 0ms
schema:
- name: carfinder
  path: .
  commands:
    build:
      status: true
      method: make build
    run:
      status: true
      method: build/carfinder
  args:
    - server
    - start
    - -addr=0.0.0.0:8888
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
